# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_directory',
            field=models.CharField(blank=True,
                                   help_text='Directory in whic'
                                             'h the code to be scanned is stored',
                                   max_length=2000, null=True),
        ),
    ]
