language: python
python: 2.7

services:
  - postgresql
  - redis-server
  - celery

addons:
  postgresql: "9.5"

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

before_script:
  - pycodestyle --exclude=migrations,settings.py,lib,tests,tmp --max-line-length=100 .
  - psql -c "CREATE DATABASE scancode;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd260d20442f274ff140
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
